#!/usr/bin/env bash

#CIBLE=/Volumes/New\ Volume/rsync
CIBLE=framboise:/mnt/PIHDD/rsync
HOME=/Users/slabbe
DOSSIERS="bin Misc Desktop Documents GitBox Movies Music Pictures" # .ssh
RSYNC="rsync -za --rsh=ssh --progress"

echo "Sauvegarde du HOME dans $CIBLE ..."
for DOSSIER in $DOSSIERS
do
    echo -n "Sauvegarde de /Users/slabbe/$DOSSIER ..."
    time $RSYNC $HOME/$DOSSIER "$CIBLE"
done

echo -n "Sauvegarde de zotero ..."
time $RSYNC $HOME/Library/Application\ Support/Firefox/Profiles/67393lr7.default/zotero "$CIBLE"

echo -n "Sauvegarde de Library/Application Support/gramps ..."
time $RSYNC $HOME/Library/Application\ Support/gramps "$CIBLE"


#recover
#rsync -za --progress /media/slabbe/New\ Volume/rsync/Movies ~
#rsync -za --progress /media/slabbe/New\ Volume/rsync/Music ~
#rsync -za --progress /media/slabbe/New\ Volume/rsync/Pictures ~
#rsync -za --progress /media/slabbe/New\ Volume/rsync/gramps ~

# Comme New Volume est en NTFS, il fait de la merde pour les permissions...
# https://superuser.com/questions/91935/how-to-chmod-all-directories-except-files-recursively
# find Pictures -type d -exec chmod 750 {} +
# find Movies   -type d -exec chmod 750 {} +
# find Musique  -type d -exec chmod 750 {} +
# find Pictures -type f -exec chmod 640 {} +
# find Movies   -type f -exec chmod 640 {} +
# find Musique  -type f -exec chmod 640 {} +


