#!/usr/bin/env bash

#CIBLE=/Volumes/New\ Volume/rsync         # OSX
#CIBLE=framboise:/mnt/PIHDD/rsync         # Raspbery pi
CIBLE=/media/slabbe/New\ Volume/rsync     # on Linux

HOME=/home/slabbe

#DOSSIERS="Documents Videos Musique Images Zotero"
DOSSIERS="Documents Musique Images Zotero"
RSYNC="rsync -za --rsh=ssh --progress"

echo "Sauvegarde du HOME dans $CIBLE ..."
for DOSSIER in $DOSSIERS
do
    echo -n "Sauvegarde de /Users/slabbe/$DOSSIER ..."
    time $RSYNC $HOME/$DOSSIER "$CIBLE"
done

#recover
#rsync -za --progress /media/slabbe/New\ Volume/rsync/Movies ~
#rsync -za --progress /media/slabbe/New\ Volume/rsync/Music ~
#rsync -za --progress /media/slabbe/New\ Volume/rsync/Pictures ~
#rsync -za --progress /media/slabbe/New\ Volume/rsync/gramps ~

# Comme New Volume est en NTFS, il fait de la merde pour les permissions...
# https://superuser.com/questions/91935/how-to-chmod-all-directories-except-files-recursively
# find Pictures -type d -exec chmod 750 {} +
# find Movies   -type d -exec chmod 750 {} +
# find Musique  -type d -exec chmod 750 {} +
# find Pictures -type f -exec chmod 640 {} +
# find Movies   -type f -exec chmod 640 {} +
# find Musique  -type f -exec chmod 640 {} +


