#!/usr/bin/env bash
#
# EXAMPLES (from rsync man page):
#
#     rsync -Cavz . arvidsjaur:backup
#     
#     get:
#            rsync -avuzb --exclude '*~' samba:samba/ .
#     put:
#            rsync -Cavuzb . samba:samba/
#     sync: get put
#
# EXAMPLES (from Arnaud Casteigts):
#
#     rsync -qzac --rsh=ssh --progress --delete --delete-excluded --force
# 
# QUELQUES OPTIONS DE RSYNC:
#
#     -v, --verbose               increase verbosity
#     -q, --quiet                 suppress non-error messages
#     -a, --archive               archive mode; same as -rlptgoD (no -H)
#     -z, --compress              compress file data during the transfer
#     -c, --checksum              skip based on checksum, not mod-time & size
#         --delete                delete extraneous files from dest dirs
#         --delete-excluded       also delete excluded files from dest dirs
#         --force                 force deletion of dirs even if not empty
#         --progress              show progress during transfer
#     -b, --backup                make backups (see --suffix & --backup-dir)
#     -u, --update                skip files that are newer on the receiver
#     -C, --cvs-exclude           auto-ignore files in the same way CVS does
#     -n, --dry-run               show what would have been transferred
#
# COMMENTAIRES:
#
#     L'option -c (checksum) prend 1min36s versus seulement 3s.
#
# TODO:
#
#     Faire un test de dry run avant de possiblement supprimer des fichiers avec un -f
#     (avoir un comportement comme git push).

THIS=`uname -n`
OPTIONS="-zua --rsh=ssh --progress --delete --delete-excluded --force"

# Forced: sget -f
if [[ ! -z $1 && $1 == "-f" ]]; then
    echo "Forced Synchronization server -> $THIS"
    rsync $OPTIONS labri:Documents/ $HOME/Documents/
    echo "We change the .last file whose content is now:"
    uname -n >> $HOME/Documents/.last
    cat $HOME/Documents/.last
    echo "We update the .last file on the server side ..."
    rsync $OPTIONS $HOME/Documents/.last labri:Documents/
    exit 0
fi

# Check the .last file to see if local machine is in there
if ssh labri cat Documents/.last | grep --quiet "$THIS"
then
    echo "Nothing new on the server."
    exit 0
else
    echo "Other computers pushed changes to the server."
fi

# Running a dry-run
echo "Running rsync command in dry-run mode ..."
rsync $OPTIONS --dry-run labri:Documents/ $HOME/Documents/
echo -n "Proceed with rsync (y/n)? "
read answer
if echo "$answer" | grep -iq "^y" ;then
    echo "You answered Yes."
    echo "Synchronization server -> $THIS"
    rsync $OPTIONS labri:Documents/ $HOME/Documents/
    echo "We change the .last file whose content is now:"
    uname -n >> $HOME/Documents/.last
    cat $HOME/Documents/.last
    echo "We update the .last file on the server side ..."
    rsync $OPTIONS $HOME/Documents/.last labri:Documents/
else
    echo "You answered No. Aborting."
    exit 1
fi
