#!/bin/sh
# This script updates Sage and run make ptestlong only if a new develop version
# is available on github
# WARNING: Use it at your own risk because I know it does not always work well...
# Author: Sebastien Labbe, 16 dec 2015

# Remove Macports from PATH
PATH=`echo $PATH | sed -e 's/\/opt\/local\/sbin://'`
PATH=`echo $PATH | sed -e 's/\/opt\/local\/bin://'`
#echo $PATH

SAGE_ROOT=$HOME/Applications/sage-git
cd $SAGE_ROOT

# Check if there are uncommitted changes
# http://stackoverflow.com/questions/2657935
# http://stackoverflow.com/questions/3878624
if [[ -z $(git status --porcelain) ]]
then
  echo "tree is clean"
else
  echo "Error: tree is dirty, please commit changes or stash them before running this"
  exit 1
fi

git checkout develop
git fetch github develop

# Check if a pull is needed in git
# http://stackoverflow.com/questions/3258243/check-if-pull-needed-in-git
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse @{u})
BASE=$(git merge-base @ @{u})
echo "Local Branch: " $LOCAL
echo "Remote Branch:" $REMOTE
echo "Base Branch:  " $BASE
if [ $LOCAL = $REMOTE ]; then
    echo "Local develop branch is up-to-date with github, we will re-build sage anyway"
elif [ $LOCAL = $BASE ]; then
    echo "Local develop branch is behind github/develop, we need to pull"
    git pull github develop
elif [ $REMOTE = $BASE ]; then
    echo "Error: Local develop branch has commits not in github/develop."
    exit 1
else
    echo "Error: Local develop branch has diverged from github/develop."
    exit 1
fi

# Build Sage
make doc-clean
rm -rf logs
export MAKE="make -j4"
make start
export MAKE="make -j1"
make doc
export MAKE="make -j4"
make ptestlong

#TODO: clean branches merged into sage
